#!/bin/sh
set -e
masterBranch="master"

if [[ "$1" = "--help" ]] ; then
   echo "Tag master branche: ";
   echo "  - git tag <version|major|minor|patch>";
   echo ""
   echo "This command will tag master branches with properly formatted version numbers."
   exit 1;
fi

if ! [ -d .git ] ; then
	if ! [ "$(git rev-parse --is-inside-work-tree &>/dev/null; echo "${?}")" == "0" ] ; then
		echo "Current directory is not a git folder."
		exit 1;
	fi
fi

branch=$(git rev-parse --abbrev-ref HEAD)
shortBranch=$(echo $branch | cut -d'/' -f 2)

if [[ "$masterBranch" != "$shortBranch" ]]
then
    echo "We are not on the master branch, currently, please checkout first to make sure of its status"
    exit 1
fi

function parse {
    version=$(git tag -l [0-9]*.[0-9]*.[0-9]* | sort --version-sort --field-separator=. | tail -n1)

    if [ -z "$version" ]
    then
        version="0.0.0"
    fi

    patchpart="${version##*.}"
    majorpart="${version%.*}"
    minorpart="${majorpart#*.}"
    majorpart="${majorpart%.*}"
}

# pull and checkout master
echo "Pull $masterBranch from origin"
git pull origin $masterBranch:$masterBranch
#git checkout $masterBranch

parse
echo "Current version: $majorpart.$minorpart.$patchpart"

case "$1" in
    major) version="$((majorpart+1)).0.0" ;;
    minor) version="$majorpart.$((minorpart+1)).0" ;;
    patch) version="$majorpart.$minorpart.$((patchpart+1))" ;;
    *)
        version=$1
        if [[ ! $version =~ [0-9]+\.[0-9]+\.[0-9]+ ]]
        then
            echo "Invalid version format $version"
            exit 1
        fi
        ;;
esac

echo "Tag $masterBranch with $version"
git tag -a $version -m "version: $version"

echo "Push $masterBranch to origin"
git push --follow-tags origin $masterBranch

